# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ai-autonomous-agent
metadata:
  template: ai-autonomous-agent@1.0.0

#
# Use layered provisioning to first deploy main infrastructure and then identity resources
# - https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/layered-provisioning
#
infra:
  layers:
    - name: base
      path: ./infra/base
    - name: identity
      path: ./infra/identity

#
# Hooks are invoked once per provisioning layer
#
hooks:
  preprovision:
    shell: sh
    run: ./infra/hooks/preprovision.sh
    interactive: true
  predown:
    shell: sh
    run: ./infra/hooks/predown.sh
    interactive: true

#
# When 'azd pipeline config' runs, avoid prompts by copying all variables and secrets to GitHub
# Secrets get evaluated from the Azure key vault and deployed as GitHub secrets
# - https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/using-environment-secrets.md#pipeline-config
#
pipeline:
  variables:
    - A2A_EXTERNAL_URL
    - AI_FOUNDRY_NAME
    - AZURE_CONTAINER_ENVIRONMENT_NAME
    - AZURE_CONTAINER_REGISTRY_ENDPOINT
    - AZURE_RESOURCE_GROUP
    - CONTAINER_APPS_ENVIRONMENT_ID
    - CONTAINER_REGISTRY_NAME
    - DBINIT_IMAGE_NAME
    - DEPLOYMENT_IDENTITY_ID
    - ENTRA_APP_DISPLAY_NAME
    - ENTRA_CLIENT_ID
    - ENTRA_OIDC_METADATA_URL
    - ENTRA_TENANT_ID
    - EXTERNAL_DOMAIN_NAME
    - GATEWAY_EXTERNAL_IMAGE_NAME
    - GATEWAY_INTERNAL_IMAGE_NAME
    - IDSVR_ADMIN_URL
    - IDSVR_IMAGE_NAME
    - IDSVR_RUNTIME_URL
    - KEY_VAULT_NAME
    - SERVICE_UTILITY_IMAGE_NAME
    - STORAGE_ACCOUNT_NAME
    - STORAGE_FILE_SHARE_NAME
    - UNIQUE_PREFIX
  secrets:
    - SQL_ADMIN_PASSWORD
    - ADMIN_PASSWORD
    - LICENSE_KEY
    - GATEWAY_TOKEN_EXCHANGE_SECRET
    - AGENT_TOKEN_EXCHANGE_SECRET
    - ENTRA_CLIENT_SECRET

#
# When 'azd deploy' runs, it builds a Docker image with a timestamp-based tag and pushes it the Azure container registry
# It then finds a matching 'azd-service-name' tag in bicep files, which causes services to get deployed as container apps
#
services:
  
  #
  # Build and deploy the Portfolio MCP Server from its Dockerfile
  #
  portfolio-mcp-server:
    project: src/PortfolioMcpServer
    host: containerapp
    language: csharp
    docker:
      path: ./Dockerfile
  
  #
  # Build and deploy the Autonomous Agent from its Dockerfile
  #
  autonomous-agent:  
    project: src/AutonomousAgent
    host: containerapp
    language: csharp
    docker:
      path: ./Dockerfile

  #
  # Build and deploy a utility container with which to test internal connections
  #
  utility:
    project: tools/utility
    host: containerapp
    language: docker
    docker:
      path: ./Dockerfile
