services:
  #
  # A local deployment of the Curity Identity Server for development
  #
  idsvr:
    image: idsvr:1.0.0
    hostname: idsvr
    ports:
      - 6749:6749
      - 8443:8443
    environment:
      ADMIN: 'true'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      IDSVR_RUNTIME_URL: '${IDSVR_RUNTIME_URL}'
      IDSVR_ADMIN_URL: '${IDSVR_ADMIN_URL}'
      GATEWAY_TOKEN_EXCHANGE_SECRET: '${GATEWAY_TOKEN_EXCHANGE_SECRET}'
      LICENSE_KEY: '${LICENSE_KEY}'

  #
  # The external gateway exposes the Portfolio MCP server and security components
  #
  external-gateway:
    image: kong/kong:3.9-ubuntu
    hostname: gateway-external
    ports:
      - 80:8000
    volumes:
      - ../gateway-external/local-routes.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_LOG_LEVEL: 'info'

  #
  # The internal gateway handles token exchange when the autonomous agent calls the MCP server
  # The internal gateway also does audit logging using access token attributes
  #
  internal-gateway:
    image: gateway-internal:1.0.0
    hostname: gateway-internal
    volumes:
      - ../gateway-internal/local-routes.yml:/usr/local/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,token-exchange,token-audit'
      KONG_NGINX_HTTP_LUA_SHARED_DICT: 'token-exchange 10m'
      KONG_NGINX_HTTP_LOG_FORMAT: "json_combined escape=json '{ \"time_iso8601\": \"$$time_iso8601\", \"remote_addr\": \"$$remote_addr\", \"method\": \"$$request_method\", \"uri\": \"$$request_uri\", \"status\": $$status, \"body_bytes_sent\": $$body_bytes_sent, \"request_time\": $$request_time, \"upstream_response_time\": \"$$upstream_response_time\", \"upstream_addr\": \"$$upstream_addr\", \"http_x_forwarded_for\": \"$$http_x_forwarded_for\", \"kong_request_id\": \"$$http_kong_request_id\" }'"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout json_combined"

  #
  # The local agent calls a Portfolio MCP server that runs in Docker behind gateways
  #
  portfolio-mcp-server:
    image: portfolio-mcp-server:1.0.0
    hostname: portfolio-mcp-server
    env_file:
      - ../../src/PortfolioMcpServer/.env.dockercompose
