_format_version: '2.1'
_transform: true
services:

#
# Internal requests to the MCP server's unsecured metadata endpoint
#
- name: portfolio-mcp-server-resource-metadata
  url: http://portfolio-mcp-server:3001/.well-known/oauth-protected-resource
  routes:
  - name: portfolio-mcp-server-resource-metadata
    hosts:
    - gateway-internal
    paths:
    - /portfolio-mcp-server/.well-known/oauth-protected-resource

#
# Internal requests to MCP server tools require an opaque access token
# The token exchange plugin gets a JWT access and forwards it to the MCP server
#
- name: portfolio-mcp-server-tools
  url: http://portfolio-mcp-server:3001
  routes:
  - name: portfolio-mcp-server
    hosts:
    - gateway-internal
    paths:
    - /portfolio-mcp-server
  plugins:
  - name: request-transformer
    config:
      replace:
        uri: "/$(uri_captures[1])"
  - name: token-exchange
    config:
      token_endpoint: http://idsvr:8443/oauth/v2/oauth-token
      client_id: internal-gateway-client
      client_secret: eTgxwAmBYjTl8ClEZOM7a49_Bo5oyQWjoEFNOkJ8CtU
      token_cache_seconds: 900
      target_audience: 'https://mcp.demo.example'
  - name: token-audit
 