_format_version: '2.1'
_transform: true
services:

#
# The external entry point for local computer requests from the autonomous agent to the MCP server
# Requests are routed via the internal gateway
#
- name: portfolio-mcp-server
  url: http://gateway-internal:8000/portfolio-mcp-server
  routes:
  - name: portfolio-mcp-server-resource-metadata
    hosts:
    - localhost
    paths:
    - /portfolio-mcp-server
  