<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0fce390a-0941-4c05-860d-74b97207a195</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="A2A" Version="1.0.0-preview2" />
    <PackageReference Include="A2A.AspNetCore" Version="1.0.0-preview2" />
    <PackageReference Include="Azure.AI.Projects" Version="2.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.5.0" />
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

</Project>
