on:
  workflow_dispatch:
  push:
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  #
  # The validation job checks for Microsoft conformance
  #
  validate:
    runs-on: ubuntu-latest
    if: true
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - uses: microsoft/template-validation-action@Latest
        id: validation
        with:
          useDevContainer: false
          validateAzd: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}

  #
  # The base provisioning job deploys core infrastructure like the container apps network 
  #
  deploy-base-infra:
    runs-on: ubuntu-latest
    if: true
    needs: 
      - validate
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in to az
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Log in to azd
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Deploy
        run: azd provision base --no-prompt

  #
  # The identity provisioning job deploys the authorization server and API gateways
  #
  deploy-identity-infra:
    runs-on: ubuntu-latest
    if: true
    needs: 
      - deploy-base-infra
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in to az
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Log in to azd
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Deploy
        run: azd provision identity --no-prompt
        env:
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          CONTAINER_APPS_ENVIRONMENT_ID: ${{ vars.CONTAINER_APPS_ENVIRONMENT_ID }}
          CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
          DBINIT_IMAGE_NAME: ${{ vars.DBINIT_IMAGE_NAME }}
          DEPLOYMENT_IDENTITY_ID: ${{ vars.DEPLOYMENT_IDENTITY_ID }}
          ENTRA_CLIENT_ID: ${{ vars.ENTRA_CLIENT_ID }}
          ENTRA_OIDC_METADATA_URL: ${{ vars.ENTRA_OIDC_METADATA_URL }}
          EXTERNAL_DOMAIN_NAME: ${{ vars.EXTERNAL_DOMAIN_NAME }}
          GATEWAY_EXTERNAL_IMAGE_NAME: ${{ vars.GATEWAY_EXTERNAL_IMAGE_NAME }}
          GATEWAY_INTERNAL_IMAGE_NAME: ${{ vars.GATEWAY_INTERNAL_IMAGE_NAME }}
          IDSVR_IMAGE_NAME: ${{ vars.IDSVR_IMAGE_NAME }}
          KEY_VAULT_NAME: ${{ vars.KEY_VAULT_NAME }}
          STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
          UNIQUE_PREFIX: ${{ vars.UNIQUE_PREFIX }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
          ENTRA_CLIENT_SECRET: ${{ secrets.ENTRA_CLIENT_SECRET }}
          GATEWAY_TOKEN_EXCHANGE_SECRET: ${{ secrets.GATEWAY_TOKEN_EXCHANGE_SECRET }}
          AGENT_TOKEN_EXCHANGE_SECRET: ${{ secrets.AGENT_TOKEN_EXCHANGE_SECRET }}

  #
  # The build job deploys applications when C# code is committed to main
  #
  deploy-applications:
    runs-on: ubuntu-latest
    if: true
    needs: 
      - deploy-identity-infra
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in to azd
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Deploy
        run: azd deploy --no-prompt
        env:
          AI_FOUNDRY_NAME: ${{ vars.AI_FOUNDRY_NAME }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          CONTAINER_APPS_ENVIRONMENT_ID: ${{ vars.CONTAINER_APPS_ENVIRONMENT_ID }}
          CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
          DEPLOYMENT_IDENTITY_ID: ${{ vars.DEPLOYMENT_IDENTITY_ID }}
          EXTERNAL_DOMAIN_NAME: ${{ vars.EXTERNAL_DOMAIN_NAME }}
          KEY_VAULT_NAME: ${{ vars.KEY_VAULT_NAME }}
          AZURE_CONTAINER_REGISTRY_ENDPOINT: ${{ vars.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
          AGENT_TOKEN_EXCHANGE_SECRET: ${{ secrets.AGENT_TOKEN_EXCHANGE_SECRET }}

  #
  # Set the 'if' flag to true for this job and to false for other jobs to tear down the deployment
  #
  teardown:
    if: false
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in to az
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Log in to azd
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Deploy
        run: azd down --force --purge --no-prompt
